### ISSUE TITLE
Reporte de Practica2 Equipo Mana

### ISSUE THREAD

**Issue by Arlet04** [SistemasTecTlaxiaco/actividad-3-practica-de-costos-web-food#1]
[Reporte de Practica2 Equipo Mana.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-costos-web-food/files/14315564/Reporte.de.Practica2.Equipo.Mana.pdf)

**Comment by josealfredo79** [comment]
Calificacion 20
